1. 분류_wine 종류

🍷 와인의 종류를 분류해보자  
데이터의 결측치, 이상치에 대해 처리하고 분류모델을 사용하여 정확도, F1 score, AUC 값을 산출하시오.  
제출은 아래 예시와 같이 result변수를 가진 dataframe 형태로 제출하시오.

In [95]:
# 답안 제출 참고
# 아래 코드는 예시이며 변수명 등 개인별로 변경하여 활용
# write.csv(data.frame변수,"result.csv",row.names = FALSE)

In [96]:
############### 실기환경 복사 영역 ###############
import pandas as pd
import numpy as np
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.datasets import load_wine
# 와인 데이터셋을 로드합니다.
wine = load_wine()
x = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.DataFrame(wine.target)
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
 stratify=y,
random_state=2023)
x_test = pd.DataFrame(x_test)
x_train = pd.DataFrame(x_train)
y_train = pd.DataFrame(y_train)
x_test.reset_index()
y_train.columns = ['target']
############### 실기환경 복사 영역 ###############

1. 라이브러리 및 데이터 확인
2. 데이터 탐색 (EDA)
3. 데이터 전처리 및 분리
4. 모델링 및 평가
5. 예측값 제출

In [97]:
import pandas as pd
import numpy as np

1. 라이브러리 및 데이터확인

   train과 test 데이터를 준다.

In [98]:
print(wine.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [99]:
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [100]:
x = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.DataFrame(wine.target)

In [101]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify = y, random_state = 2024)
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)
y_train = pd.DataFrame(y_train)
x_test.reset_index()
y_train.columns = ['target']

In [102]:
print(x_train.head(3))
print(x_test.head(3))
print(y_train.head(3))
print(y_test.head(3))

    alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
39    14.22        3.99  2.51               13.2      128.0           3.00   
83    13.05        3.86  2.32               22.5       85.0           1.65   
68    13.34        0.94  2.36               17.0      110.0           2.53   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
39        3.04                  0.20             2.08             5.10  0.89   
83        1.59                  0.61             1.62             4.80  0.84   
68        1.30                  0.55             0.42             3.17  1.02   

    od280/od315_of_diluted_wines  proline  
39                          3.53    760.0  
83                          2.01    515.0  
68                          1.93    750.0  
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
81     12.72        1.81  2.20               18.8       86.0           2.20   
88     11.64        2.06  2.46  

In [103]:
print(x_train.dtypes, '\n')
print(x_test.dtypes, '\n')
print(y_train.dtypes, '\n')
print(y_test.dtypes, '\n')

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_wines    float64
proline                         float64
dtype: object 

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_w

In [104]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(142, 13)
(36, 13)
(142, 1)
(36, 1)


In [105]:
print(x_train.info(), '\n')
print(x_test.info(), '\n')
print(y_train.info(), '\n')
print(y_test.info(), '\n')

<class 'pandas.core.frame.DataFrame'>
Index: 142 entries, 39 to 6
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       142 non-null    float64
 1   malic_acid                    142 non-null    float64
 2   ash                           142 non-null    float64
 3   alcalinity_of_ash             142 non-null    float64
 4   magnesium                     142 non-null    float64
 5   total_phenols                 142 non-null    float64
 6   flavanoids                    142 non-null    float64
 7   nonflavanoid_phenols          142 non-null    float64
 8   proanthocyanins               142 non-null    float64
 9   color_intensity               142 non-null    float64
 10  hue                           142 non-null    float64
 11  od280/od315_of_diluted_wines  142 non-null    float64
 12  proline                       142 non-null    float64
dtypes: float64(

In [106]:
print(x_train.describe(), '\n')
print(x_test.describe(), '\n')

          alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  142.000000  142.000000  142.000000         142.000000  142.000000   
mean    13.020845    2.303099    2.377606          19.652113  100.978873   
std      0.820986    1.103127    0.272854           3.389025   14.747746   
min     11.030000    0.740000    1.700000          11.400000   70.000000   
25%     12.345000    1.540000    2.222500          17.125000   89.000000   
50%     13.050000    1.845000    2.365000          19.500000   98.000000   
75%     13.717500    3.030000    2.580000          21.500000  109.500000   
max     14.750000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     142.000000  142.000000            142.000000       142.000000   
mean        2.322394    2.064155              0.354225         1.608380   
std         0.649696    1.004367              0.119219         0.577259   
min         0.9

In [107]:
print(y_train.describe(), '\n')
print(y_test.describe(), '\n')

           target
count  142.000000
mean     0.936620
std      0.773816
min      0.000000
25%      0.000000
50%      1.000000
75%      2.000000
max      2.000000 

               0
count  36.000000
mean    0.944444
std     0.790820
min     0.000000
25%     0.000000
50%     1.000000
75%     2.000000
max     2.000000 



In [108]:
print(x_train.isnull().sum())

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64


In [109]:
Q1 = x_train.quantile(0.25)
Q3 = x_train.quantile(0.75)
IQR = Q3 - Q1
outliers = ((x_train < (Q1 - 1.5 * IQR)) | (x_train > (Q3 + 1.5 * IQR))).sum()
print(outliers)

alcohol                         0
malic_acid                      2
ash                             2
alcalinity_of_ash               3
magnesium                       2
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 2
color_intensity                 2
hue                             1
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64


In [110]:
# Q1 = x_test.quantile(0.25)
# Q3 = x_test.quantile(0.75)
# IQR = Q3 - Q1
outliers = ((x_test < (Q1 - 1.5 * IQR)) | (x_test > (Q3 + 1.5 * IQR))).sum()
print(outliers)

# test 데이터도 train의 IQR로 계산해야함

alcohol                         0
malic_acid                      1
ash                             1
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64


In [111]:
x_train['malic_acid'] = np.where(x_train['malic_acid'] < (Q1 - 1.5 * IQR)['malic_acid'], (Q1 - 1.5 * IQR)['malic_acid'], x_train['malic_acid'])
x_train['malic_acid'] = np.where(x_train['malic_acid'] > (Q3 + 1.5 * IQR)['malic_acid'], (Q3 + 1.5 * IQR)['malic_acid'], x_train['malic_acid'])

In [112]:
Q1 = x_train.quantile(0.25)
Q3 = x_train.quantile(0.75)
IQR = Q3 - Q1
outliers = ((x_train < (Q1 - 1.5 * IQR)) | (x_train > (Q3 + 1.5 * IQR))).sum()
print(outliers)

alcohol                         0
malic_acid                      0
ash                             2
alcalinity_of_ash               3
magnesium                       2
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 2
color_intensity                 2
hue                             1
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64


In [113]:
upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR

def clip(s):
    return np.where(s < lower[s.name], lower[s.name], np.where(s > upper[s.name], upper[s.name], s))

In [114]:
x_train = x_train.apply(clip, axis = 0)
x_test = x_test.apply(clip, axis = 0)

In [115]:
Q1 = x_train.quantile(0.25)
Q3 = x_train.quantile(0.75)
IQR = Q3 - Q1

upper = Q3 + 1.5 * IQR
lower = Q1 - 1.5 * IQR

여기까지 결측치 확인, 이상치 제거했고 변수처리 해줘야함. **파생변수 생성이나 원-핫 인코딩**

여기까지 전처리 및 분리가 끝이났고, 모델링을 해야함
좋은 모델링을 위해 validation 활용

In [116]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train['target'], test_size = 0.2, stratify = y_train['target'], random_state = 2025) 

In [117]:
print(x_train.head(3))
print(x_val.head(3))
print(y_train.head(3))
print(y_val.head(3))

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
154    12.58        1.29  2.10               20.0      103.0           1.48   
150    13.50        3.12  2.62               24.0      123.0           1.40   
90     12.08        1.83  2.32               18.5       81.0           1.60   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
154        0.58                  0.53             1.40              7.6  0.58   
150        1.57                  0.22             1.25              8.6  0.59   
90         1.50                  0.52             1.64              2.4  1.08   

     od280/od315_of_diluted_wines  proline  
154                          1.55    640.0  
150                          1.30    500.0  
90                           2.27    480.0  
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
177    14.13        4.10  2.74               24.5       96.0           2.05   
103    11.82        

In [118]:
print(x_train.dtypes)
print(x_val.dtypes)
print(y_train.dtypes)
print(y_val.dtypes)

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_wines    float64
proline                         float64
dtype: object
alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_win

In [119]:
print(x_train.shape)
print(x_val.shape)
print(y_train.shape)
print(y_val.shape)

(113, 13)
(29, 13)
(113,)
(29,)


In [120]:
print(x_train.info)
print(x_val.info)
print(y_train.info)
print(y_val.info)

<bound method DataFrame.info of      alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
154    12.58        1.29  2.10               20.0     103.00           1.48   
150    13.50        3.12  2.62               24.0     123.00           1.40   
90     12.08        1.83  2.32               18.5      81.00           1.60   
69     12.21        1.19  1.75               16.8     140.25           1.85   
138    13.49        3.59  2.19               19.5      88.00           1.62   
..       ...         ...   ...                ...        ...            ...   
174    13.40        3.91  2.48               23.0     102.00           1.80   
116    11.82        1.47  1.99               20.8      86.00           1.98   
55     13.56        1.73  2.46               20.5     116.00           2.96   
145    13.16        3.57  2.15               21.0     102.00           1.50   
4      13.24        2.59  2.87               21.0     118.00           2.80   

     flavanoids  no

In [123]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state = 2025)
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=2025)

In [124]:
y_pred = rf.predict(x_val)

이렇게하면 학습이 끝났고 그다음에 검증을 해야함

분류모델의 성능평가해야함. 분류에서는 정확도, F1 Score, AUC의 등으로 평가한다.

In [139]:
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score

In [140]:
acc = accuracy_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred, average = 'macro')
# auc = roc_auc_score(y_val, y_pred)

In [141]:
print(acc, '\n')
print(f1, '\n')

1.0 

1.0 



이제 검증까지 끝났으면, 제출을 해야한다

In [142]:
y_result = rf.predict(x_test)
print(y_result)

[1 1 2 0 0 0 1 2 2 0 1 1 2 1 2 0 2 1 1 0 1 0 0 0 0 1 0 1 0 2 1 1 2 1 2 2]


아니면 해당 내용으로 분류될 확률?

In [156]:
y_result = rf.predict_proba(x_test)
print(y_result)

[[0.34 0.64 0.02]
 [0.03 0.96 0.01]
 [0.02 0.19 0.79]
 [0.93 0.06 0.01]
 [0.84 0.12 0.04]
 [1.   0.   0.  ]
 [0.01 0.9  0.09]
 [0.   0.13 0.87]
 [0.   0.   1.  ]
 [0.97 0.03 0.  ]
 [0.   0.71 0.29]
 [0.1  0.9  0.  ]
 [0.03 0.05 0.92]
 [0.01 0.98 0.01]
 [0.01 0.   0.99]
 [0.77 0.19 0.04]
 [0.   0.05 0.95]
 [0.   0.87 0.13]
 [0.06 0.91 0.03]
 [0.7  0.3  0.  ]
 [0.   0.94 0.06]
 [0.92 0.08 0.  ]
 [0.95 0.05 0.  ]
 [0.94 0.06 0.  ]
 [0.99 0.01 0.  ]
 [0.29 0.64 0.07]
 [0.93 0.07 0.  ]
 [0.04 0.95 0.01]
 [0.95 0.05 0.  ]
 [0.   0.11 0.89]
 [0.02 0.79 0.19]
 [0.01 0.88 0.11]
 [0.   0.02 0.98]
 [0.08 0.83 0.09]
 [0.   0.1  0.9 ]
 [0.01 0.   0.99]]


In [160]:
# pd.DataFrame({'result':y_result}).to_csv('수험번호.csv', index=False)

pd.DataFrame(y_result, columns = [f'prob_class_{c}' for c in rf.classes_]).to_csv('수험번호.csv', index= False)