# RNN에 대한 기본 개념을 이해해보자
- RNN은 이전 데이터가 다음 데이터에 영향을 주는 경우, 적합한 학습이 될 수 있다.
- Keras의 SimpleRNN을 사용해보자

# char 단위로 학습하기
- 4개의 글자(char)가 들어가면 다음 글자(char)를 맞추는 모델링을 해보자
- hello, apple, happy, drink, hose
- 단어사전(14개) : h, e, l, o, a, p, 

In [4]:
import numpy as np
x = np.array(
    [[1 if j == i else 0 for j in range(14)] for i in range(15)],
    dtype=int
)

# X : 5개의 단어 데이터의 앞에서부터 4개 글자(char)
# 원-핫 인코딩의 방법으로 글자를 숫자로 표현
# ex) 'hell'의 'h'는 [1,0,0,0,0,0,0,0,0,0,0,0,0,0] 로 표현
# ex) 'hell'이 모델에 입력되면 'o'가 출력되는 학습
#     'hell' -> X, o -> y
X = np.array([
    [[1,0,0,0,0,0,0,0,0,0,0,0,0,0],  [0,1,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0]],  # 'hell'
    [[0,0,0,0,1,0,0,0,0,0,0,0,0,0],  [0,0,0,0,0,1,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0]],  # 'appl'
    [[1,0,0,0,0,0,0,0,0,0,0,0,0,0],  [0,0,0,0,1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0,0,0,0,0]],  # 'happ'
    [[0,0,0,0,0,0,0,1,0,0,0,0,0,0],  [0,0,0,0,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0,0]],  # 'drin'
    [[1,0,0,0,0,0,0,0,0,0,0,0,0,0],  [0,0,0,1,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,1]]   # 'hous'
])

# y : o, e, y, k, e
# 정답 글자들을 한 번더 묶어줌 -> 2차원 y : o, e, y, k, e
y = np.array([
 [0,0,0,1,0,0,0,0,0,0,0,0,0,0], # 'hell' -> 'o'
 [0,1,0,0,0,0,0,0,0,0,0,0,0,0], # 'appl' -> 'e'
 [0,0,0,0,0,0,1,0,0,0,0,0,0,0], # 'happ' -> 'y'   
 [0,0,0,0,0,0,0,0,0,0,0,1,0,0], # 'drin' -> 'k'
 [0,1,0,0,0,0,0,0,0,0,0,0,0,0]  # 'hous' -> 'e' 
])

print(x.shape)  # (15, 14)
print(y.shape)  # (15, 15)
print(x)
print(y)


(15, 14)
(5, 14)
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
